### ISSUE TITLE
Crashes at Main() method

### ISSUE THREAD

**Issue by gpeipman** [ssrdio/IdentityUI#1]
Added NuGet package to default ASP.NET Core web application, configured it by manual and app crashes on startup with error: 

System.InvalidOperationException: 'Scheme already exists: Identity.Application'

**Comment by GregorSpagnolo** [comment]
can you share Startup.cs code? 
we submitted sample app at /samples/IdentityUI.Sample/IdentityUI.Sample

**Comment by UrbanVogrin** [comment]
Closing this issue because it has been inactive for a few months.
