### ISSUE TITLE
Existing User Added To a Group And Made Group Admin Role does not show up in Assigned Roles Of User

### ISSUE THREAD

**Issue by sykyck** [ssrdio/IdentityUI#18]
I created a group say SSRD company and i added existing user nino.olivetto@ssrd.io and assigned Group Role Group Admin to it but the corresponding role cannot be seen in Assigned Roles UI of user Detail

**Comment by UrbanVogrin** [comment]
@sykyck In the Assigned Roles UI on the user details page only global roles are show, if you would like to see user role in the group you need to go to that group details page.
