### ISSUE TITLE
2FA unclear instructions

### ISSUE THREAD

**Issue by webDeveloper95** [ssrdio/IdentityUI#2]
I'm trying to set-up 2FA for your application, and I noticed that your instructions are not completely clear.

1. You did not provide which 2FA application should we install on mobile device, which i find confusing for some users.

2. You have button **Show code** which reveals code. It would be nice if another click would also hide the code. I recommend also text toggling from Show code/Hide code.

![image](https://user-images.githubusercontent.com/60654746/73745930-6bd27100-4754-11ea-9f40-e08839bfd0a3.png)

**Comment by UrbanVogrin** [comment]
Changed instructions and added show/hide toggle button. 3e54563b15ff69e7aed1a81d975f1b14289e1059
