### ISSUE TITLE
Change password errors

### ISSUE THREAD

**Issue by webDeveloper95** [ssrdio/IdentityUI#3]
When you fail to change password error banner is shown. The problem is, that it disappear too soon and you are unable to read whole message. 

![image](https://user-images.githubusercontent.com/60654746/73746276-1d71a200-4755-11ea-925e-c0a08ad455dd.png)

**Comment by UrbanVogrin** [comment]
Changed so that error alert does not close automatically. acf60848f682cff1a2b86296d0e246fae21d7dc5
